# Generated by Django 5.0.6 on 2024-08-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groccery', '0004_alter_cart_phone_alter_cart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('phone', 'product')},
        ),
    ]
